using System;
using System.Collections.Generic;

namespace MonoCloud.SDK.UsersBackend.Models;

/// <summary>
/// Problem Details class
/// </summary>
public class ProblemDetails
{
   /// <summary>
   /// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when de-referenced, it provide human-readable documentation for the problem type.
   /// </summary>
   public string? Type { get; set; }

   /// <summary>
   /// A short, human-readable summary of the problem type.
   /// </summary>
   public string? Title { get; set; }

   /// <summary>
   /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
   /// </summary>
   public int? Status { get; set; }

   /// <summary>
   /// A human-readable explanation specific to this occurrence of the problem.
   /// </summary>
   public string? Detail { get; set; }

   /// <summary>
   /// A URI reference that identifies the specific occurrence of the problem.It may or may not yield further information if de-referenced.
   /// </summary>
   public string? Instance { get; set; }

   /// <summary>
   /// Specifies the errors corresponding to the model properties, if any.
   /// </summary>
   public Dictionary<string, List<string>>? Errors { get; set; }
}


